#+TITLE: nonopoly

* Master-Version
+ NoNopoly-Spiel mit Commandline-Bedienung.
+ Benutzung:
  1. Ins Basisverzeichnins =nonopolyful= (/Users/johannes/Box
     Sync/Dsl-Akademie/forschung/Vorhaben/ZustandsloseApplikationen/nonopolyful) gehen.
  2. Im Terminalfenster
     #+BEGIN_SRC shell
     clj -m nonopolyful.core
     #+END_SRC
     eingeben.
* Web-Version
(gebaut nach [[https://www.safaribooksonline.com/library/view/living-clojure/9781491909270/ch07.html][Carin Meier]])
+ NoNopoly-Spiel als Server mit Web-Oberfläche
+ Benutzung:
  1. Web-Server starten: In Terminalfenster =lein ring server=
     eingeben; Ausgabe:
     #+BEGIN_SRC shell
2018-05-13 23:46:55.580:INFO:oejs.Server:jetty-7.6.13.v20130916
2018-05-13 23:46:55.680:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:3000
Started server on port 3000
     #+END_SRC
     TRACE-Ausgaben gehen ins Terminalfenster
  2. Browser wird geöffnet mit  localhost:3000
  3. in Browser Url =http://localhost:3000/nonopoly.html= eingeben
+ für Entwicklung: 
  1. In another terminal run the following:
     #+BEGIN_SRC shell
lein cljsbuild auto
     #+END_SRC
     This command will start a process that will compile your
     core.cljs file to JavaScript. It will continously monitor the
     file for  changes, and recompile when it detects a change.
  2. Browser-Connected REPL: We can attach a Clojurescript REPL to the
     browser and be able to make the changes in the REPL happen on the
     frontend. Using the same basic tools as before we will be able to
     enter code into our REPL and have a web page magically update in
     front of our eyes. This is quite exciting for experimentation and
     rapid feedback when working with the frontend.
 
     To do this, there is another cljsbuild REPL to use when we want to attach our browser to it:
     #+BEGIN_SRC shell
-> lein trampoline cljsbuild repl-listen
Running ClojureScript REPL, listening on port 9000.
To quit, type: :cljs/quit
ClojureScript:cljs.user>
     #+END_SRC
* Planck-Version (Clojurescript)
+ [[https://github.com/planck-repl/planck][Planck]] ist eine stand-alone Clojurescript-Repl basierend auf
  JavascriptCore (JS engine von [[https://webkit.org][WebKit]]; verfügbar für Mac and Linux.
+ Doku: [[http://planck-repl.org]]
+ Planck ist ein [[https://lambdaisland.com/guides/clojure-repls/bootstrapped-clojurescript-repls][bootstrapped Clojurescript-Compiler]]
+ Damit ist es möglich, NoNopoly als Clojurescript-Version laufen zu
  lassen.
+ Benutzung
  1. Im Terminal ins Verzeichnis
     =ZustandsloseApplikationen/nonopolyplanck= wechseln
  2. 
     a. Kommando =plk -m nonopoly.core= eingeben, oder
     b. =plk= eingeben, Clojurescript-Repl wird gestartet. Dort die
        folgenden Eingaben vornehmen:
        #+BEGIN_SRC shell
(require '[nonopoly.core :as nop])
(nop/-main)
        #+END_SRC
+ Implementierung: Aus den clj-Dateien der Clojure-Version werden in
  cljc-Dateien kopiert.
+ Es wird die lokale Bibliothek nonopolyfulc verwendet.
+ Da Standard-Clojurescript kein =read-line= kennt muss in
  =welten-cljs= der Namespace =planck.core= importiert werden.
* Re-frame-Version (Clojurescript)
+ Auf der Suche nach einer Entsprechung für die [[https://guide.elm-lang.org/architecture/][Elm Architecture]] in
  Clojurescript auf [[https://github.com/Day8/re-frame][re-frame]] (A Reagent Framework For Writing SPAs, in
  Clojurescript) gestoßen
+ NoNopoly-Variante in nonopolyref; keine Änderungen des Models
  (nonopolyful) erforderlich
+ Zustandsverwaltung wird vom Framework übernommen (wie bei Elm); man
  programmiert strikt funktional
+ Anlegen einer Html-Datei nicht erforderlich
+ Programm läuft vollständig in Javascript im Browser 
+ Benutzung
  1. Im Terminal ins Verzeichnis
     =ZustandsloseApplikationen/nonopolyref= wechseln
  2. Kommando =lein do clean, figwheel= eingeben
  3. Im Browser [[http://localhost:3449/]] aufrufen 
     (Server wird hier nur für den Start der Anwendung gebraucht.)
     oder
  4. Im Browser die index.html Datei öffnen
     (Server wird hier nicht benötigt.)
+ Implementierung:
  + vgl. die „6-Domino-Theorie” in der re-frame-Dokumentation
* Reagent-Version (Clojurescript)
+ Für einfache Anwendungen (wie NoNopoly) ist re-frame vielleicht
  etwas „überdimensioniert“. Hier kommt man auch mit [[https://github.com/reagent-project/reagent][Reagent]] (a simple
  ClojureScript interface to React.) zurecht.
+ NoNopoly-Variante in nonopolyref; keine Änderungen des Models
  (nonopolyful) erforderlich
+ Zustandsverwaltung muss man hier mithilfe eines =reagent/atom=
  selbst vornehmen.
+ Anlegen einer Html-Datei nicht erforderlich
+ Programm läuft vollständig in Javascript im Browser 
+ Benutzung
  1. Im Terminal ins Verzeichnis
     =ZustandsloseApplikationen/nonopolyrey= wechseln
  2. Kommando =lein do clean, figwheel= eingeben
  3. Im Browser [[http://localhost:3449/]] aufrufen 
     (Server wird hier nur für den Start der Anwendung gebraucht.)
     oder
  4. Im Browser die index.html Datei öffnen
     (Server wird hier nicht benötigt.)

